 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet build
       - run: dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\..\TestResults\{assembly}-Results.xml"
       - store_test_results: 
           path: TestResults
